version: '3.8'

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ner_user
      POSTGRES_PASSWORD: ner_password
      POSTGRES_DB: ner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: